### ISSUE TITLE
[FIX] 설정에서 관심법안 선택 버그 수정

### ISSUE THREAD

**Issue by lenamin** [Gaongil/Gaongil#41]
## 💡 Issue

설정뷰에서 관심법안을 다시 선택하면 탭바가 이중으로 뜨는 버그 수정하기 

## 📝  todo
- [ ] 설정뷰에서의 관심법안화면에서 완료 버튼 생성 
- [ ] 기존 시작하기 버튼 없애기 
- [ ] 기존에 선택했던 카테고리가 선택되어 있도록 구현 
- [ ] 완료 버튼 누르면 TodayLawView로 이동하도록 설정

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/99120199/201448501-38986e75-cf71-4455-a4c7-003eb0b5d960.png)
